# Added by Yang B.

datasets:
  clef_2023_caption: # name of the dataset builder
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://s3.openi.org.cn/opendata/attachment/d/7/d7f3534a-91e4-42c9-8b46-abacf67deb30?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20231229%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231229T085006Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22train.json%22&X-Amz-Signature=d89cad0617e026effbedd41606702c2c1847fda2e3922ac30ee0bcebfff2378a
          storage:
              - clef_2023_caption/train.json
        val:
          url: 
              - https://s3.openi.org.cn/opendata/attachment/d/9/d9f24499-d0d7-44dd-bfac-7912f64391da?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20231229%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231229T085254Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22val.json%22&X-Amz-Signature=97a74f23f40143f662ff751f156ee43987d4a7a82e583443b9c8f6b82676c5f7 
          storage:
              - clef_2023_caption/val.json
        test:
          url:
              - https://s3.openi.org.cn/opendata/attachment/f/0/f0465de9-1c79-4f61-9662-cad5005e55a8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=1fa9e58b6899afd26dd3%2F20231229%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20231229T085254Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%3D%22test.json%22&X-Amz-Signature=8fb42c9cab2fb99acafe44b980a9df445972f28b74728a751f981ba05f3b7072
          storage: 
              - clef_2023_caption/test.json
      images:
        storage: clef_2023_caption/
